# Generated by Django 5.1.2 on 2024-11-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dirección', models.CharField(max_length=200, verbose_name='Dirección')),
                ('imagen', models.ImageField(blank=True, upload_to='locales_asociados/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Local Asociado',
                'verbose_name_plural': 'Locales Asociados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='ChrisdeParis/', verbose_name='Imagen del producto')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
