# Generated by Django 5.1.2 on 2024-12-02 04:34

import chris_de_paris.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris_de_paris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localasociado',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='locales_asociados/', validators=[chris_de_paris.models.validate_image], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='ChrisdeParis/', validators=[chris_de_paris.models.validate_image], verbose_name='Imagen del producto'),
        ),
    ]
