# Generated by Django 4.2.7 on 2024-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='menus/', verbose_name='Archivo PDF del Menú')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Menú PDF',
                'verbose_name_plural': 'Menús PDF',
            },
        ),
    ]
