# Generated by Django 5.1.2 on 2024-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupdf',
            name='nombre_menu',
            field=models.CharField(default='Menú General', max_length=200, verbose_name='Nombre del Menú'),
            preserve_default=False,
        ),
    ]
